//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceTime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraceTime.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITY (LAST 30 DAYS).
        /// </summary>
        public static string ActivityLast30Days {
            get {
                return ResourceManager.GetString("ActivityLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplication.
        /// </summary>
        public static string AplicationLabel {
            get {
                return ResourceManager.GetString("AplicationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application runs in the background.
        /// </summary>
        public static string AppRunsBckg {
            get {
                return ResourceManager.GetString("AppRunsBckg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video / Audio - {0}.
        /// </summary>
        public static string AudioStatusFormatLng {
            get {
                return ResourceManager.GetString("AudioStatusFormatLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart error.
        /// </summary>
        public static string AutostartError {
            get {
                return ResourceManager.GetString("AutostartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (BG).
        /// </summary>
        public static string BackgroundStatusLng {
            get {
                return ResourceManager.GetString("BackgroundStatusLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details (card).
        /// </summary>
        public static string DetailsCards {
            get {
                return ResourceManager.GetString("DetailsCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the program.
        /// </summary>
        public static string EndAppLng {
            get {
                return ResourceManager.GetString("EndAppLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLang {
            get {
                return ResourceManager.GetString("EnglishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Focus).
        /// </summary>
        public static string FocusStatusLng {
            get {
                return ResourceManager.GetString("FocusStatusLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string HyphenLng {
            get {
                return ResourceManager.GetString("HyphenLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE (PAUSE).
        /// </summary>
        public static string IdleLng {
            get {
                return ResourceManager.GetString("IdleLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (IN BACKGROUND).
        /// </summary>
        public static string InBckgLng {
            get {
                return ResourceManager.GetString("InBckgLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        public static string LanguageChangeLang {
            get {
                return ResourceManager.GetString("LanguageChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change requires a restart. Would you like to restart now?.
        /// </summary>
        public static string LanguageChangeRestartNote {
            get {
                return ResourceManager.GetString("LanguageChangeRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24h.
        /// </summary>
        public static string Last24hLng {
            get {
                return ResourceManager.GetString("Last24hLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        public static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity:.
        /// </summary>
        public static string LastActivityLabel {
            get {
                return ResourceManager.GetString("LastActivityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring....
        /// </summary>
        public static string MonitoringStatus {
            get {
                return ResourceManager.GetString("MonitoringStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active window.
        /// </summary>
        public static string NoActiveWindow {
            get {
                return ResourceManager.GetString("NoActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ACTIVITY.
        /// </summary>
        public static string NoActivityLng {
            get {
                return ResourceManager.GetString("NoActivityLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TraceTime.
        /// </summary>
        public static string OpenTraceTimeLng {
            get {
                return ResourceManager.GetString("OpenTraceTimeLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string PolishLang {
            get {
                return ResourceManager.GetString("PolishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string PostsLng {
            get {
                return ResourceManager.GetString("PostsLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Mode (hide titles).
        /// </summary>
        public static string PrivacyModeLabel {
            get {
                return ResourceManager.GetString("PrivacyModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        public static string RangeAllTime {
            get {
                return ResourceManager.GetString("RangeAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string RangeLabel {
            get {
                return ResourceManager.GetString("RangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string RangeMonth {
            get {
                return ResourceManager.GetString("RangeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string RangeWeek {
            get {
                return ResourceManager.GetString("RangeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTED RANGE.
        /// </summary>
        public static string SelectedRange {
            get {
                return ResourceManager.GetString("SelectedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m still monitoring your time!.
        /// </summary>
        public static string StillMonitoringTime {
            get {
                return ResourceManager.GetString("StillMonitoringTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary statistics.
        /// </summary>
        public static string SummaryStatistics {
            get {
                return ResourceManager.GetString("SummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string TableLng {
            get {
                return ResourceManager.GetString("TableLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live View.
        /// </summary>
        public static string TabLive {
            get {
                return ResourceManager.GetString("TabLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (s).
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer error.
        /// </summary>
        public static string TimerErrorLng {
            get {
                return ResourceManager.GetString("TimerErrorLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY (LIVE).
        /// </summary>
        public static string TodayLiveHeader {
            get {
                return ResourceManager.GetString("TodayLiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayLng {
            get {
                return ResourceManager.GetString("TodayLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total activity.
        /// </summary>
        public static string TotalActivity {
            get {
                return ResourceManager.GetString("TotalActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceTime.
        /// </summary>
        public static string TraceTimeLng {
            get {
                return ResourceManager.GetString("TraceTimeLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceTime - Activity Monitoring.
        /// </summary>
        public static string TTActivityMonitoringLng {
            get {
                return ResourceManager.GetString("TTActivityMonitoringLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string ViewCharts {
            get {
                return ResourceManager.GetString("ViewCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View:.
        /// </summary>
        public static string ViewLabel {
            get {
                return ResourceManager.GetString("ViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string YesterdayLang {
            get {
                return ResourceManager.GetString("YesterdayLang", resourceCulture);
            }
        }
    }
}
